export const cuadros = [
    { "id": "2", "name": "cuadroimg2", "description": "Vida mental - Dibujo personal - Fibrofacil 20x30x0,9 cm", "img": "../nowen/galeria/cuadroimg2.png" },
    { "id": "3", "name": "cuadroimg3", "description": "El ojo que todo lo ve - Dibujo personal - Fibrofacil 20x30x1,2 cm", "img": "../nowen/galeria/cuadroimg3.png" },
    { "id": "4", "name": "cuadroimg4", "description": "Lindsey Stirling - Álbum Artemis - Fibrofacil 30x20x0,9 cm", "img": "../nowen/galeria/cuadroimg4.png" },
    { "id": "5", "name": "cuadroimg5", "description": "The last meaw - Retrato de una instagramer - Fibrofacil 45x39x0,5cm", "img": "../nowen/galeria/cuadroimg5.png" },
    { "id": "6", "name": "cuadroimg6", "description": "Pareja eterna - Pedido para un regalo especial de aniversario - Fibrofacil 45X50X1,2 cm", "img": "../nowen/galeria/cuadroimg6.png" },
    { "id": "7", "name": "cuadroimg7", "description": "Harry Potter - Mi escena favorita de la saga - Fibrofacil 45x39x0,5 cm", "img": "../nowen/galeria/cuadroimg7.png" },
    { "id": "8", "name": "cuadroimg8", "description": "Familia Michi - mini cuadro Fibrofacil 8x8x0,5 cm", "img": "../nowen/galeria/cuadroimg8.png" },
    { "id": "9", "name": "cuadroimg9", "description": "Mariposa - Mini cuadro de Fibrofacil 8x8x0,5cm", "img": "../nowen/galeria/cuadroimg9.png" },
    { "id": "10", "name": "cuadroimg10", "description": "Perfil - Mini cuadro Fibrofacil 8x8x0,5 cm", "img": "../nowen/galeria/cuadroimg10.png" },
    { "id": "11", "name": "cuadroimg11", "description": "Plano medio - Mini cuadro Fibrofacil 8x8x0,5 cm", "img": "../nowen/galeria/cuadroimg11.png" },
    { "id": "12", "name": "cuadroimg12", "description": "Hijo gatuno - Mini cuadro Fibrofacil 8x8x0,5 cm", "img": "../nowen/galeria/cuadroimg12.png" },
    { "id": "13", "name": "cuadroimg13", "description": "Amistad - Retrato de una escena de la pelicula 'El viaje de Chihiro' - Mini cuadro 8x8x0,5 cm", "img": "../nowen/galeria/cuadroimg13.png" },
    { "id": "14", "name": "cuadroimg14", "description": "Gatos por la tarde - Mini cuadro Fibrofacil 8x8x0,5 cm", "img": "../nowen/galeria/cuadroimg14.png" },
    { "id": "15", "name": "cuadroimg15", "description": "Pablo Agustin - Retrato de un creador de contenido - Fibrofacil 30x20x1,2 cm", "img": "../nowen/galeria/cuadroimg15.png" },
    { "id": "16", "name": "cuadroimg16", "description": "Hermanos - Créditos del dibujo a quien lo merezca - Fibrofacil 35x55x1,2 cm", "img": "../nowen/galeria/cuadroimg16.png" },
    { "id": "17", "name": "cuadroimg17", "description": "Mulan, una decisión que lo cambia todo - Fibrofacil 55x35x1,2 cm", "img": "../nowen/galeria/cuadroimg17.png" },
    { "id": "18", "name": "cuadroimg18", "description": "Mirada - Creditos por el dibujo a quien lo merezca - Fibrofacil 40x30x1,2 cm", "img": "../nowen/galeria/cuadroimg18.png" },
    { "id": "19", "name": "cuadroimg19", "description": "Alimentos - Cuadro a pedido de un amante de la cosecha - Fibrofacil 60x50x1,2 cm", "img": "../nowen/galeria/cuadroimg19.png" },
    { "id": "20", "name": "cuadroimg20", "description": "Familia de rosas - Fibrofacil 45x50x1,2 cm", "img": "../nowen/galeria/cuadroimg20.png" },
    { "id": "21", "name": "cuadroimg21", "description": "Recuerdo de un padre - Fibrofacil 40x30x1,2 cm - Entintado con rojo.", "img": "../nowen/galeria/cuadroimg21.png" },
    { "id": "22", "name": "cuadroimg22", "description": "Colibrí al vuelo - Fibrofacil 40x30x1,2 cm - Coloreado con tinta china y entintado con negro.", "img": "../nowen/galeria/cuadroimg22.png" },
    { "id": "23", "name": "cuadroimg23", "description": "Caballero de Dark Souls III - Fibrofacil de 80X50x0,5 cm - un trabajo realizado con una gubia y un mini torno.", "img": "../nowen/galeria/cuadroimg23.png" },
    { "id": "24", "name": "cuadroimg24", "description": "Lindsey Stirling, una artista poco usual - 30x30x0,9cm - Fibrofacil de 9mm entintado con negro.", "img": "../nowen/galeria/cuadroimg24.png" },
]