export const cuadros = [
    { "id": "2", "name": "Vida mental", "description": "Dibujo personal de un día caótico", "footer": "Fibrofacil 20x30x0,9 cm", "img": "../nowen/galeria/cuadroimg2.png" },
    { "id": "3", "name": "El ojo que todo lo ve", "description": "Dibujo personal de un día lleno de trabajo", "footer": "Fibrofacil 20x30x1,2 cm", "img": "../nowen/galeria/cuadroimg3.png" },
    { "id": "4", "name": "Lindsey Stirling", "description": "Álbum Artemis", "footer": "Fibrofacil 30x20x0,9 cm", "img": "../nowen/galeria/cuadroimg4.png" },
    { "id": "5", "name": "The last meaw", "description": "Retrato de una instagramer", "footer": "Fibrofacil 45x39x0,5cm", "img": "../nowen/galeria/cuadroimg5.png" },
    { "id": "6", "name": "Pareja eterna", "description": "Pedido para un regalo especial de aniversario", "footer": "Fibrofacil 45X50X1,2 cm", "img": "../nowen/galeria/cuadroimg6.png" },
    { "id": "7", "name": "Harry Potter", "description": "Mi escena favorita de la saga", "footer": "Fibrofacil 45x39x0,5 cm", "img": "../nowen/galeria/cuadroimg7.png" },
    { "id": "8", "name": "Familia Michi", "description": "Mini cuadro", "footer": "Fibrofacil 8x8x0,5 cm", "img": "../nowen/galeria/cuadroimg8.png" },
    { "id": "9", "name": "Mariposa", "description": "Mini cuadro", "footer": "Fibrofacil 8x8x0,5cm", "img": "../nowen/galeria/cuadroimg9.png" },
    { "id": "10", "name": "Perfil", "description": "Mini cuadro", "footer": "Fibrofacil 8x8x0,5 cm", "img": "../nowen/galeria/cuadroimg10.png" },
    { "id": "11", "name": "Plano medio", "description": "Mini cuadro", "footer": "Fibrofacil 8x8x0,5 cm", "img": "../nowen/galeria/cuadroimg11.png" },
    { "id": "12", "name": "Hijo gatuno", "description": "Mini cuadro", "footer": "Fibrofacil 8x8x0,5 cm", "img": "../nowen/galeria/cuadroimg12.png" },
    { "id": "13", "name": "Amistad", "description": "Retrato de una escena de la pelicula 'El viaje de Chihiro'", "footer": "Mini cuadro 8x8x0,5 cm", "img": "../nowen/galeria/cuadroimg13.png" },
    { "id": "14", "name": "Gatos por la tarde", "description": "Mini cuadro", "footer": "Fibrofacil 8x8x0,5 cm", "img": "../nowen/galeria/cuadroimg14.png" },
    { "id": "15", "name": "Pablo Agustin", "description": "Retrato de un creador de contenido", "footer": "Fibrofacil 30x20x1,2 cm", "img": "../nowen/galeria/cuadroimg15.png" },
    { "id": "16", "name": "Hermanos", "description": "Créditos del dibujo a quien lo merezca", "footer": "Fibrofacil 35x55x1,2 cm", "img": "../nowen/galeria/cuadroimg16.png" },
    { "id": "17", "name": "Mulan", "description": "Una decisión que lo cambia todo", "footer": "Fibrofacil 55x35x1,2 cm", "img": "../nowen/galeria/cuadroimg17.png" },
    { "id": "18", "name": "Mirada", "description": "Creditos por el dibujo a quien lo merezca", "footer": "Fibrofacil 40x30x1,2 cm", "img": "../nowen/galeria/cuadroimg18.png" },
    { "id": "19", "name": "Alimentos", "description": "Cuadro a pedido de un amante de la cosecha", "footer": "Fibrofacil 60x50x1,2 cm", "img": "../nowen/galeria/cuadroimg19.png" },
    { "id": "20", "name": "Familia de rosas", "description": "", "footer": "Fibrofacil 45x50x1,2 cm", "img": "../nowen/galeria/cuadroimg20.png" },
    { "id": "21", "name": "Colibrí al vuelo", "description": "Coloreado con tinta china y entintado con negro.", "footer": "Fibrofacil 40x30x1,2 cm", "img": "../nowen/galeria/cuadroimg22.png" },
    { "id": "22", "name": "Caballero de Dark Souls III", "description": "Un trabajo realizado con una gubia y un mini torno.", "footer": "Fibrofacil de 80X50x0,5 cm", "img": "../nowen/galeria/cuadroimg23.png" },
    { "id": "23", "name": "Lindsey Stirling", "description": "Una artista poco usual", "footer": "30x30x0,9cm. Fibrofacil de 9mm entintado con negro.", "img": "../nowen/galeria/cuadroimg24.png" },
]